import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('bookings.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblBookings ( 
        booking_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        passenger_id INTEGER, -- ID of the passenger (optional)
        driver_id INTEGER, -- ID of the driver (optional)
        trip_id INTEGER, -- ID of the trip (optional)
        title TEXT NOT NULL, -- Title of the book (required) 
        number INTEGER UNIQUE NOT NULL, -- Unique booking number 
        FOREIGN KEY (passenger_id) 
            REFERENCES tblBookings(passengers_id) -- Foreign key constraint referencing the pasengers table

        FOREIGN KEY (driver_id) 
            REFERENCES tblUsers(driver_id) -- Foreign key constraint referencing the taxi drivers info table
        
        FOREIGN KEY (trip_id) 
            REFERENCES tblBookings(trip_id) -- Foreign key constraint referencing the trips table
        )


    )



""") -- create the bookings table if it doesn't exist

