import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('passengers.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblPassengers ( 
        passenger_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        user_id INTEGER, -- ID of the user (optional)
        number_customers INTEGER UNIQUE NOT NULL, -- Unique number of customers
        pickup_location TEXT NOT NULL, -- Pickup location (required)
        dropoff_address TEXT NOT NULL -- Address of the dropoff location (required)
    
        FOREIGN KEY (user_id) 
            REFERENCES tblBookings(user_id) -- Foreign key constraint referencing the user table

        )


        ) 
""") -- create the passengers table if it doesn't exist
