import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('payments.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblBookings ( 
        payment_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        booking_id INTEGER, -- ID of the booking (optional)
        amount_id INTEGER, -- Payment amount (optional)
        payment_date TEXT NOT NULL, -- Date of payment
        payment_method TEXT NOT NULL -- Method of payment (e.g., credit card, cash, etc.)
    
        FOREIGN KEY (trip_id) 
            REFERENCES tblBookings(trip_id) -- Foreign key constraint referencing the pasengers table

        
        )


    )



""") -- create the bookings table if it doesn't exist






