import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('review.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblBookings ( 
        review_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        booking_id INTEGER, -- ID of the booking (optional)
        trip_id INTEGER, -- ID of the trip (optional)
        title TEXT NOT NULL, -- Title of the book (required) 
        number INTEGER UNIQUE NOT NULL, -- Unique booking number 
        pickup_location TEXT NOT NULL, -- Pickup location (required)
        dropoff_address TEXT NOT NULL -- Address of the dropoff location (required)
    
        FOREIGN KEY (trip_id) 
            REFERENCES tblBookings(trip_id) -- Foreign key constraint referencing the trips table

        FOREIGN KEY (booking_id) 
            REFERENCES tblBookings(booking_id) -- Foreign key constraint referencing the bookings table
        
        FOREIGN KEY (taxi driver_id) 
            REFERENCES tblBookings(taxi_driver_id) -- Foreign key constraint referencing the taxi drivers info table
        )


    )



""") -- create the bookings table if it doesn't exist





