import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('taxi_drivers_info.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblBookings ( 
        driver_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        name TEXT NOT NULL, -- Driver name (required) 
        dob TEXT NOT NULL, -- Driver date of birth (required)
        license_number TEXT UNIQUE NOT NULL, -- Unique license number
        

        FOREIGN KEY (users_id) 
            REFERENCES tblBookings(users_id) -- Foreign key constraint referencing the pasengers table

        
        )


    )



""") -- create the bookings table if it doesn't exist




