import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('trip.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblBookings ( 
        trip_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        booking_id INTEGER, -- ID of the booking (optional)
        vehicle_id INTEGER, -- ID of the vehicle (optional)
        title TEXT NOT NULL, -- Title of the book (required) 
        number INTEGER UNIQUE NOT NULL, -- Unique booking number 
        pickup_location TEXT NOT NULL, -- Pickup location (required)
        dropoff_address TEXT NOT NULL -- Address of the dropoff location (required)
    
        
        FOREIGN KEY (vehicle_id) 
            REFERENCES tblVehicles(vehicle_id) -- Foreign key constraint referencing the vehicles table
        
        FOREIGN KEY (booking_id) 
            REFERENCES tblBookings(booking_id) -- Foreign key constraint referencing the bookings table
        )


    )



""") -- create the bookings table if it doesn't exist
