import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('users.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblUsers ( 
        user_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        user_name TEXT NOT NULL, -- Title of the book (required) 
        user_password TEXT UNIQUE NOT NULL, -- Unique password for the user
        
    )
""") -- create the users table if it doesn't exist

