import sqlite3 -- import library for SQLite database operations

connection = sqlite3.connect('vehicle.db') -- connect to the database (or create it if it doesn't exist)
print("Database connection established.")
cursor = connection.cursor() -- create a cursor object to execute SQL commands
cursor.execute("""
    CREATE TABLE IF NOT EXISTS tblBookings ( 
        vehicle_id INTEGER PRIMARY KEY AUTOINCREMENT, -- Unique ID auto-generated by DB 
        regristration_number TEXT UNIQUE NOT NULL, -- Unique registration number for the vehicle
        mot_expiry_date TEXT NOT NULL, -- MOT expiry date for the vehicle
        insurance_expiry_date TEXT NOT NULL, -- Insurance expiry date for the vehicle
        car_model TEXT NOT NULL, -- Car model (required)
        car-color TEXT NOT NULL, -- Car color (required)
        driver_id INTEGER NOT NULL, -- Driver ID (optional, can be NULL if no driver is assigned)
        seat_capacity INTEGER NOT NULL, -- Set seat capacity for the vehicle
        car_tax_expiry_date TEXT NOT NULL, -- Car tax expiry date for the vehicle
       
        FOREIGN KEY (driver_id) 
            REFERENCES tblUsers(driver_id) -- Foreign key constraint referencing the taxi drivers info table

        ) 


""") 


""" -- create the bookings table if it doesn't exist